name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v@2

      - name: Install dependencies
        run: npm install

      #- name: Run tests
      #  run: npm run test:headless

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: success()
        uses: rajesh-sacumen/travis-demo@master
        with:
          github_token: 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
          publish_dir: dist/travis-demo
          enable_jekyll: true
